sudo: required
language: python
python:
- '3.6'
services:
- docker
before_install:
- sudo rm -f /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname  -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
- docker -v
script:
- export APP_VERSION=$(git tag | tail -n1)
- echo $APP_VERSION
- docker-compose -f docker-compose-dev.yml build
- docker images | grep 'web\|celery'
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
    #branch: master
env:
  global:
env:
  DOCKERHUB_USERNAME: novavic
  global:
    secure: c1MxnYwWuDad7nVkDDd+ll6vKBqvTvFxq8S11HP5x5k8KUlG9xLIE76Xo4g2I4n47pKW3iNmeoTnUUQOBc6u19MCgjOxl/hxsr9ts4RozHnzwMnt43gQHon4xeEoQHPmq0oOa8oU7ZeP51GZNnqiFj3cq0+2B+OHPJa+AD7dUnbGjNjzuyQ0wXoe37/4cGWX1ewF0ZRYLHOBSzvLwgN+Xn8jDL5OhW5y4kixMEN5zyxyGj3jPex0o3bjc6zYXMa8PxjreLxetD+nv/9cJ47MZK31X/uhQ1EKzjVG/i5DP8V9ANcltGZwWsTSDFNlwymVoB+eQcEAQcxyHn+beUGIqjJDnBuLe7fdgwrijUQbHa9CdsUNfbwUNRMaWFRVwIWiBTnH0uAxZ5Ht433HF/5QjRfQXGs1UEaxPQTOaU7VeNkKAAoBFp2cM8Wes+t6g1vvS7NFvYr5PzewIJs7YUPUQVQo7ebtItrsq+W+bec4xjzFZEL0ZsFKjgeJGdmrC6B22Q9KAw3s1qjzAp+P2fpinUPeGoavAltskMq3evsd4EH2jLdEpGliBjpLzAgReebWrktjww4PHUzZMk+kFYC3wHusZXTRAE/flHZToU/blPZiyfCC0hi+0O7NxUZCtH2Ho1OoNm3IyHRxLuHz1e41ic33+6EmvvGpr6Datqwsd/w=
notifications:
  email:
    on_success: never
    on_failure: always
