sudo: required
language: python
python:
- '3.6'
services:
- docker
before_install:
- sudo rm -f /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname  -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose --version
- docker -v
script:
- export APP_VERSION=$(git tag | tail -n1)
- echo $APP_VERSION
- docker-compose -f docker-compose-dev.yml build
- docker images | grep 'web\|celery'
deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true
    #branch: master
env:
  global:
  - secure: oAv801zUMhX9AV4jBLbfwYMbVIrKQBdpj3CPS9zpDTfUM+mUJ9l649G71Z9ttkjygMaaChU0tKjCERN/bT1XEEDPBV4Mi2joQIpeb6RYzQFMmKb0X02gQqSKVWlo0/+sFmK4bjXtBHPmlJzyAc5Cltd66wCsslUVcAL5r9enu7atcBkqeZElABoiHHqiMo06ymTVNCUE7fl5Vsg7s6vZOKTsxmk2JF4Czxe+xKt6vG6qhnh/1BJZdTy+TxfYdrKCYctLE2HAbgTI0h4xsOpv8QlnW4Kk1GwzCphzV6OeC71wBgL4d38VIfX6shc9Vm7FBrhP/NcvoM/YEipRCu3PYA317uggjj7hngvUvHXSkiIaih/Yd/rgiQ7XYnMclSpmAaCv6EC2asjCw7dnpHiJCSYweUmwFLJt925syZOiU8thZPVDhymb4pcfvF1tNBtrKljUh4J/AQoSHOUZZELApGUsVeiu5EDzVHKFLUg27WvYTwuyWD014Wwm3SDav9ActkW0TrkjJg3/lADpNV1rm1FyZtGYGnDKy0lQpyWdw9VB1DA5xxFm9kT7goHtxICXAOn06PnJophkorlSE3oMUcoH4GK4/NwQSg/wcizM2edAV6lq/bSF3l4Q1f6MH/31mo+Pfr9LBUJwyzf+pppvo4S8irIpUrbIW6LubcEdPOY=
  - secure: kOmSAscPwqdAl3AHtBvOLsqVo8OsWxRTNLan1PMDyGLZ9CXJ0ChEZ2fUl7dUPNx3h3QArGY4buem7nWA6tI0cC1E1AtiqmfB3DSH2xN/trgBWhLH69Q2yQC8tv06AftsyRfhXtPkSJNpdI0q7Z+Sp+i1vvvsJv1ZMvwMe+29H2OgM55Vs1XcUWQf95vWHnN6sL3t8d3iKy7BI/IS8Yo7QvC4tXAK+YLrIpU0LkQ1nmvFHog5SyNTgbhdTVc7b9bUjsbNZOPA0xy0DM1KuOtD6+xB2gdgDbUgEs1g4xLozpycedBnYZ5PGl3ilwinKyJC2fPRcH0l71btfMUSuxG7o4TzFdMDCL9brfnx89tbpUcbPijTgEfqhCbFmnmHXfJktCXk6TpZk0m3avkbhUro7jCwkSdZAAL8Of3pvwaRkJgQyZKV0fT0IuI7hR5hnyV6f6aTUEsFxjS5VVFspEyUXsAENs7oCr2oxlDI27vV0Kn4U2uEtJRjXzdkXsMDlmVWsRH1cgQruX7XtsLvqSvm1Zsb4XAYNinxOLCk10Q78ngYVKPcIKB2m/JEqvqjmkABkPCXeV8420Afqf0z974g/jmuRLexWxO+fahVmRFdJ1Z+jW7MsZtaGt+zKKDUnW6mDVBLKo0ffQdGAfIZpstEIEFiTf4Pgx1yvmfEsAOkRSw=
notifications:
  email:
    on_success: never
    on_failure: always
